os: 
  - linux
language: minimal
branches:
  only:
  - master
  - production
script:
- sudo apt-get install -y libxml2-utils
- bash check-saml-metadata/check_saml_metadata.sh metadata/
env:
  global:
  - ENCRYPTION_LABEL: f641f006de37
after_success:
- sudo apt-get install -y ant
- bash CI-assets/deploy.sh
deploy:
  api_key:
    secure: "$GITHUB_TOKEN"
  file: "gh-pages/aggregated_feed_master.xml"
  on:
    tags: true
  overwrite: true
  provider: releases
  skip_cleanup: true
notifications:
  email:
    on_success: change
    on_failure: always
