os: 
  - linux
language: minimal
branches:
  only:
  - master
  - production
script:
- sudo apt-get install -y libxml2-utils
- bash check-saml-metadata/check_saml_metadata.sh metadata/
env:
  global:
  - ENCRYPTION_LABEL: f641f006de37
notifications:
  email:
    on_success: change
    on_failure: always