os: 
  - linux
language: minimal
branches:
  only:
  - master
  - production
script:
- sudo apt-get install -y libxml2-utils
- bash check-saml-metadata/check_saml_metadata.sh metadata/
env:
  global:
  - ENCRYPTION_LABEL: f641f006de37
  - COMMIT_AUTHOR_EMAIL: "spf-qa-bot@clarin.eu"
after_success:
- sudo apt-get install -y ant
- bash CI-assets/deploy.sh
deploy:
  provider: pages
  local_dir: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
notifications:
  email:
    on_success: change
    on_failure: always
